config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :contacts
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated :user do
    root 'trips#index', as: :authenticated_root
  end

  root "welcome#index"

  #route to share urls
  namespace :public, path: ':url_slug' do
    get '/', to: 'trips#index', as: :trips
    get '/:id', to: 'trips#show', as: :trip
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates_presence_of :full_name

  validates :phone_number, :presence => true, :if => "email.blank?"
  validates :email, :presence => true, :if => "phone_number.blank?"
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user

  has_many :trip_contacts
  has_many :contacts, through: :trip_contacts
  has_and_belongs_to_many :contacts, join_table: 'trip_contacts'

  accepts_nested_attributes_for :trip_contacts

  validates_presence_of :title, :description, :check_in_time, :latitude, :longitude


  def check_in_time_has_past?
    DateTime.now >= check_in_time
  end
end

app/models/trip_contact.rb
class TripContact < ApplicationRecord
  belongs_to :trip
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trips
  has_many :contacts
  
  validates_uniqueness_of :full_name

  before_save :generate_unique_url_slug!

  private
    def generate_unique_url_slug!
      self.url_slug = full_name.parameterize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :show_flash

  private

  def show_flash
    flash.now[:notice] = "Found the about page!" if request.path == '/pages/about'
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def index
    @contacts = current_user.contacts.order(:full_name)
  end

  def new
    @contact = Contact.new
  end

  def edit
    @contact = current_user.contacts.find(params[:id])
  end

  def update
    @contact = current_user.contacts.find(params[:id])
    @contact.update(contact_params)

    redirect_to contacts_path
  end

  def create
    @contact = Contact.create(contact_params.merge(user: current_user))
    
    flash[:error] = 'A contact needs least a name and a phone number or email address' unless @contact.valid?
    
    redirect_to contacts_path
   

  end

  private
    def contact_params
      params.require(:contact).permit(:full_name, :phone_number, :email)
    end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @trips = current_user.trips.includes(:user).order('created_at desc')
  end

  def new
    @trip = Trip.new
    @contacts = current_user.contacts
  end

  def edit
    @trip = current_user.trips.find(params[:id])
  end

  def show
    @trip = current_user.trips.find(params[:id])
  end

  def update
    @trip = current_user.trips.find(params[:id])
    @trip.update(trip_params)
    respond_to do |format|
      format.html{ redirect_to trip_path(@trip) }
      format.js{ render :update }
    end
    
  end

  def create
    contact_ids = params[:contact_ids]

    @trip = Trip.create(trip_params.merge(user: current_user))

    if @trip.valid?
      render :create
    else
      render :new
    end
  end

  def destroy
    @trips = current_user.trips
    
    @trip = @trips.find(params[:id])
    @trip.destroy

    render :index
  end


  private
    def trip_params
      params.require(:trip).permit(:title, :description, :checked_in, :check_in_time, :latitude, :longitude, contact_ids: [])
    end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    trips_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    trips_path
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact.html.haml
.row.justify-content-center{id: dom_id(contact)}
  .col-md-6
    .box.m1y
      .trip-title
        = contact.full_name
        .pull-right
          %small.small
            = link_to edit_contact_path(contact), remote: true do
              %i.fa.fa-pencil
      %small.small
        %i.fa.fa-phone
        = contact.phone_number
      %br
      %small.small
        %i.fa.fa-envelope-o
        = contact.email

app/views/contacts/_edit.html.haml
.row.justify-content-center{id: dom_id(contact)}
  .col-md-6
    .box.m1y
      = form_for contact, url: contact_path(contact), method: :put do |f|
        .form-group
          %i.fa.fa-user
          = f.text_field :full_name, class: 'form-control'
        .form-group
          %i.fa.fa-phone
          = f.text_field :phone_number, class: 'form-control'
        .form-group
          %i.fa.fa-envelope-o
          = f.text_field :email, class: 'form-control'
        .form-group
          = f.submit 'Update', class: 'btn btn-primary'

app/views/contacts/_new.html.haml
.row.justify-content-center
  .col-md-12
    .box.m1y
      = form_for contact, url: contacts_path, method: :post do |f|
        .form-group
          %i.fa.fa-user
          = f.text_field :full_name, class: 'form-control', autofocus: true, placeholder: 'Full Name'
        .form-group
          %i.fa.fa-phone
          = f.text_field :phone_number, class: 'form-control', placeholder: '8005556666'
        .form-group
          %i.fa.fa-envelope-o
          = f.text_field :email, class: 'form-control', placeholder: 'e@mail.com'

        %hr
          = f.submit 'Save', class: 'btn btn-success'

app/views/contacts/edit.js.erb
$('#<%= dom_id(@contact) %>').replaceWith('<%= j(render partial: "edit", locals: {contact: @contact}) %>');

app/views/contacts/index.html.haml
.container
  .row.justify-content-center
    .col-md-4.text-center
      = link_to 'New Contact', new_contact_path, remote: true, class: 'btn btn-primary'
  #new-contact-form
  #contact-list.m1y
  - @contacts.each do |contact|
    = render partial: 'contact', locals: {contact: contact}

app/views/contacts/new.js.erb
$("#new-contact-form").html('<%= j(render partial: "new", locals: {contact: @contact}) %>')

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.haml
.container
  %nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
    %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    = link_to "Trailmate", root_path, class: 'navbar-brand'
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        - if user_signed_in?
          %li.nav-item
            = link_to 'Contacts', contacts_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Logout', destroy_user_session_path, class: 'nav-link', method: :delete
        - else
          %li.nav-item
            = link_to 'Login', new_user_session_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Sign Up', new_user_registration_path, class: 'nav-link btn btn-secondary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Trailmate" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Trailmate" %>">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <script>
      feather.replace()
    </script>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>

<div class="jumbotron">
  <h1 class="display-4">About the Website</h1>
  <p class="lead">
    This web application was created with
    <%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
    from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
  </p>
</div>

app/views/trips/_edit.html.haml
= form_for @trip, url: trip_path(trip), method: :put do |f|
  .pad4y
    .row
      .col-md-12
        .form-group
          %label
          Title
          %span.text-danger= @trip.errors.messages[:title].join
          = f.text_field :title, class: 'form-control', placeholder: 'ex: Longs Peak Highline'
        .form-group
          %label
          Description
          %span.text-danger= @trip.errors.messages[:description].join
          = f.text_area :description, class: 'form-control', rows: '7', placeholder: 'This message will be sent to your contacts. Some people use this field for local SAR contacts, or emergency instructions...'

        .form-group
          %label
          Check In Time
          %span.text-danger= @trip.errors.messages[:check_in_time].join
          = f.text_field :check_in_time, class: 'form-control datetimepicker'
      .col-md-12
        .form-group
          %label Contacts
          %ul.list-group
            = f.collection_check_boxes :contact_ids, current_user.contacts.all, :id, :full_name do |b|
              %li.list-group-item
                = b.check_box
                = b.object.full_name
    .row
      .col-md-12
        = f.submit 'Update', class: 'btn btn-primary'

        = link_to 'cancel', "#", onclick: "$(this).closest('#edit-trip-form').html('')"

        = link_to trip_path(trip), method: :delete do
          .text-muted.fr Delete

app/views/trips/_new.html.haml
.row.justify-content-center
  .col-md-12
    .box.m1y
      = form_for @trip, url: trips_path, method: :post, remote: true do |f|
        .row
          .col-md-4
            .form-group
              %label
              Title
              %span.text-danger= @trip.errors.messages[:title].join
              = f.text_field :title, class: 'form-control', placeholder: 'ex: Longs Peak Highline'
            .form-group
              %label
              Description
              %span.text-danger= @trip.errors.messages[:description].join
              = f.text_area :description, class: 'form-control', rows: '7', placeholder: 'This message will be sent to your contacts. Some people use this field for local SAR contacts, or emergency instructions...'

            .form-group
              %label
              Check In Time
              %span.text-danger= @trip.errors.messages[:check_in_time].join
              = f.text_field :check_in_time, class: 'form-control datetimepicker'

          .col-md-4
            %ul.list-group
              = f.collection_check_boxes :contact_ids, current_user.contacts.all, :id, :full_name do |b|
                %li.list-group-item
                  = b.check_box(checked: "false")
                  = b.object.full_name
              %li.list-group-item
                =link_to 'Add new contacts', contacts_path


          .col-md-4
            %span.text-danger= @trip.errors.messages[:latitude].join
            %input.form-control{id: 'searchTextField', type: 'text'}
            #trip-location-map{style: 'height: 400px; width: 100%;'}
            = f.hidden_field :latitude, placeholder: 'lat'
            = f.hidden_field :longitude, placeholder: 'lon'
        %hr
          = f.submit 'Save', class: 'btn btn-success'
          = link_to 'cancel', "#"

:javascript
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });

  
  if (typeof(google) == "undefined"){
    var script = document.createElement('script');
        script.type = 'text/javascript';
        script.src = "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}&libraries=places&callback=init";
        document.body.appendChild(script);
  }else{
    init();
  }

  function init(){
    var map = new google.maps.Map(document.getElementById('trip-location-map'), {
      center: {lat: 34, lng: -118},
      zoom: 8
    });

    var marker = new google.maps.Marker({
        position: {lat: 34, lng: -118},
        map: map,
        draggable: true
    })

    var autocomplete = new google.maps.places.Autocomplete(document.getElementById('searchTextField'));
    google.maps.event.addListener(autocomplete, 'place_changed', function () {
      var place = autocomplete.getPlace();

      var latitude = place.geometry.location.lat();
      var longitude = place.geometry.location.lng();

      var myLatlng = new google.maps.LatLng(latitude,longitude);
      marker.setPosition(myLatlng);
      map.panTo(myLatlng);

      $("#trip_latitude").val(latitude);
      $("#trip_longitude").val(longitude);
    });

    google.maps.event.addListener(marker, 'dragend', function(event){
      latitude = event.latLng.lat();
      longitude = event.latLng.lng();
      console.log('dragged');
      console.log(latitude);
      $("#trip_latitude").val(latitude);
      $("#trip_longitude").val(longitude);
    });
  };

app/views/trips/_trip.html.haml
.row.justify-content-center{id: dom_id(trip)}
  .col-md-6
    .box.m1y
      .trip-title
        .i.fa.fa-clock-o{class: (trip.check_in_time_has_past? ? 'text-danger' : 'text-success').to_s}
        = link_to trip.title, trip_path(trip)
        .pull-right
          %small
            = link_to 'public share url', public_trip_url(trip.user.url_slug, trip.id), target: '_blank'
      .trip-description.pad2b
        = trip.description

      %small Intended check in time:
      %small.text-muted
        = trip.check_in_time.in_time_zone.strftime('%b %e, %l:%M %p %Z')

      - if trip.checked_in?
        .text-success
          %i.fa.fa-check
          #{trip.user.full_name} has checked in
      - else
        = link_to trip_path(trip, trip: {checked_in: true}), method: :put, remote: true do
          .btn.btn-primary.btn-block.btn-lg.m3t Check In

app/views/trips/create.js.erb
$('#new-trip-form').html('');//clear out the form
$("#trip-list").prepend('<%= j(render partial: "trip", locals: {trip: @trip}) %>'); //new trip at the top of the list

app/views/trips/edit.js.erb
$('#edit-trip-form').html('<%= j(render partial: "edit", locals: {trip: @trip}) %>');

app/views/trips/index.html.haml
%h2.text-center.pad2b= current_user.full_name
.container
  .row.justify-content-center
    .col-md-4.text-center
      = link_to 'New Trip', new_trip_path, remote: true, class: 'btn btn-primary'
  #new-trip-form
  #trip-list.m1y
    - @trips.each do |trip|
      = render partial: 'trip', locals: {trip: trip}

    - unless @trips.any?
      .text-center
        Add some trips

app/views/trips/new.js.erb
$('#new-trip-form').html('<%= j(render partial: "new", locals: {trip: @trip}) %>');

$('.datetimepicker').datetimepicker({
  timeFormat: 'HH:00',
  dateFormat: 'yy-mm-dd',
  showMinutes: false,
});

app/views/trips/show.html.haml
%h2.text-center.pad2b= current_user.full_name
.container
  #trip-list.m1y
    = render partial: 'trip', locals: {trip: @trip}
.container
  .row.justify-content-center
    .col-md-6
      = link_to 'Edit', edit_trip_path(@trip), remote: true, class: "btn btn-secondary"
      #edit-trip-form

app/views/trips/update.js.erb
$("#<%= dom_id(@trip) %>").replaceWith('<%= j(render partial: "trip", locals: {trip: @trip}) %>')

app/views/users/shared/_links.html.haml
.shared-links
  - if controller_name != 'sessions'
    = link_to "Log in", new_session_path(resource_name)
    %br/
  - if devise_mapping.registerable? && controller_name != 'registrations'
    = link_to "Sign up", new_registration_path(resource_name)
    %br/
  - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
    = link_to "Forgot your password?", new_password_path(resource_name)
    %br/
  - if devise_mapping.confirmable? && controller_name != 'confirmations'
    = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
    %br/
  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
    = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
    %br/
  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
      %br/

app/views/welcome/index.html.haml
.container
  .row
    .col-lg-8.home-feature-text
      %h1
        Let your
        .animated-words
          %span mom
          %span girlfriend
          %span roommate
          %span boyfriend
          %span dad
          %span friends
        %br know about your adventures.
      = link_to 'Get Started', new_user_session_path, class: 'btn btn-primary btn-lg'

  .row.banner-features
    .col-lg-4
      .icon
        %i{"data-feather" => "plus-circle"}
      %p
        Create plans that show where you're headed, what you're doing, and when you'll be back.
    .col-lg-4
      .icon
        %i{"data-feather" => "share"}
      %p
        Share your plan with close friends and family so people know where you are.
    .col-lg-4
      .icon
        %i{"data-feather" => "bell"}
      %p
        They'll get sent automatic email and text message alerts if you don't check in by your scheduled time.
.home-feature-banner
  .container
    .row
      .col-lg-7
        %p "This is a great idea that we think can help SAR efforts in Colorado and around the country avoid fatal accidents. I'd encourage anyone hiking 14ers alone, or not, to utilize this service."
        .name - Colorado Search and Rescue
.testimonials.border-bottom
  .container
    .box
      %h2.text-center.pad2b More Testimonials
      .row
        .col-lg-6
          .box-skinny.m3b
            %p "It's the greatest thing ever. Kyle actually tells me what he's doing now. Before, I would only find out after the fact."
            %p.text-muted - Kyle's mom
        .col-lg-6
          .box-skinny.m3b
            %p "Sometimes he would just disappear for a few days and I was never sure whether I should be worried. This makes things a lot easier."
            %p.text-muted - Kyle's roommate
        .col-lg-6
          .box-skinny
            %p "Another Testimonial"
            %p - Bob's mom
        .col-lg-6
          .box-skinny
            %p " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate harum ullam inventore at, sit molestias! Magnam culpa pariatur fugiat necessitatibus nam."
            %p - Sarah's roommate
.about-section.pad4y
  .container
    .row.pad4y
      .col-lg-12
        %h2.text-center How it Works
        .text-center Let's break this down into a potential real-life scenario
    .container.box
      .comparison
        .row.border-bottom.no-gutters
          .col-lg-6.border-right
            .text-center
              Before Trailmate:
            .item
              .number
                1.
              %p
                It's Friday evening, and you're decided to hike a nearby peak in the morning. It's a pretty straightforward hike for your ability level.
          .col-lg-6
            .text-center
              After Trailmate:
            .item
              .number
                1.
              %p
                It's Friday evening, and you're decided to hike a nearby peak in the morning. It's a pretty straightforward hike for your ability level.

        .row.border-bottom.no-gutters
          .col-lg-6.border-right
            .item
              .number
                2.
              %p
                Your roommate is out at the bars, but you go to bed early. You don't let them, or anyone else know where you're headed because you're sure it's a straightforward hike.
          .col-lg-6
            .item
              .number
                2.
              %p
                Your roommate is out at the bars, and you go to bed early. You setup a trip on Trailmate, which notifies your roommate and another close friend about what you plan on doing. You only expect the hike to take a few hours, so you set a second notification for Saturday evening.
        .row.border-bottom.no-gutters
          .col-lg-6.border-right
            .item
              .number
                3.
              %p
                You get up early, drive to the trailhead and head out on your hike.
          .col-lg-6
            .item
              .number
                3.
              %p
                You get up early, drive to the trailhead and head out on your hike.

        .row.border-bottom.no-gutters
          .col-lg-6.border-right
            .item
              .number
                4.
              %p
                Sometime during your hike, you trip on a root and break your ankle. It's not life threatening, but you don't have signal and you're in too much pain to get to the trailhead.

          .col-lg-6
            .item
              .number
                4.
              %p
                Sometime during your hike, you trip on a root and break your ankle. It's not life threatening, but you don't have signal and you're in too much pain to get to the trailhead.

        .row.border-bottom.no-gutters
          .col-lg-6.border-right
            .item
              .number
                5.
              %p
                Your roommate is out and about all weekend, and no one reports you missing until you don't show up for work on Monday. However, no one knows where you are.
          .col-lg-6
            .item
              .number
                5.
              %p
                Your roommate and friend get notified via eamil and text on Saturday evening when you haven't checked in. They both try and get in touch with you, but when they are unsuccessful, one of them notifies the local ranger station. They include what your plan was and your general location, which is helpful for SAR.

        .row.border-bottom.no-gutters
          .col-lg-6.border-right
            .item
          .col-lg-6
            .item
              .number
                6.
              %p
                SAR finds you on the trail, trying to crawl your way back to the trailhead. They successfully extract you and deliver you to the hospital to have your broken ankle set.

        .row.border-bottom.no-gutters
          .col-lg-6.border-right
            .item
              .text-muted Conclusion:
              %h2
                You die of hypothermia.
          .col-lg-6
            .item
              .text-muted Conclusion:
              %h2 You're back home late Saturday evening, safe and sound.
      .row.justify-content-center.pad4y
        .col-lg-8.text-center
          %p Is this a morbid example? Yes. Is this an exaggerated situation? Well, not really. Unfortunately, this is a scenario that plays out every year, often with fatal consequences.


.how-it-works
  .container
    .row.justify-content-center.pad8y
      .col-lg-4
        %h2 Why?
      .col-lg-8
        %p Have you seen 127 Hours? Aron Ralston survived a canyoneering accident after being trapped for 5 days and amputating his own arm. One of the reasons his predicament was so dire was that he hadn't informed anyone of his hiking plans.
        %p I don't know about you, but I'm often guilty of similarly poor planning. While I've been lucky enough to avoid any accidents or major injuries, I often don't properly inform friends and family about my adventure plans. Sorry mom.
        %p Our goal is to provide a notification system for folks to easily inform their friends and family about where they're going and what they're doing, whether it's hiking, climbing, backcountry skiing, mountain biking, or anything else.
        %p Trailmate is not a replacement for proper planning, preparedness, or good decision-making. However, we hope that it can provide a useful service to keep the important people in your life more informed and aware.

.container
  .row.pad8y
    .col-lg-4
      %h2 FAQ
    .col-lg-8
      .faq-item
        %h3 Is this free?
        %p
          That's a great question. Would you pay a nominal monthly fee for a service like this? We'd hate for price to be a barrier for folks, especially for a product geared around safety, but it does cost us money to keep the tech running.
      .faq-item
        %h3 Is this an app?
        %p
          Not yet. V1 works via the site, email, and SMS/text only. If you want to help us turn it into one, shoot an email to kyle@kylefrost.com.
      .faq-item
        %h3 Why not use an InReach?
        %p
          InReach's and other satellite-based safety technology are amazing. However many people don't have access to these devices, or see them as overkill. Hopefully, a service like this can provide value in the middle-ground.